### ISSUE TITLE
Please release `pynamodb-attributes=0.3.1`

### ISSUE THREAD

**Issue by NazarioJL** [lyft/pynamodb-attributes#36]
Can we get a release off of commit https://github.com/lyft/pynamodb-attributes/commit/7a8ea998581e310411348eb54225438fc4d87372

**Comment by fsouza** [comment]
Published the release: https://github.com/lyft/pynamodb-attributes/releases/tag/v0.3.1

Which is now available in PyPI: https://pypi.org/project/pynamodb-attributes/0.3.1/

Thank you for contributing! 😁

**Comment by NazarioJL** [comment]
❤️
